[project]
name = "adriabox"
version = "0.1.0"
description = "A decentralized multi-tenant encrypted object storage matrix"
authors = [
    {name = "Massimiliano Pupillo", email = "massimiliano.pupillo@studio.unibo.it"},
    {name = "Sajmir Buzi", email = "sajmir.buzi@studio.unibo.it"}
]
readme = "README.md"
requires-python = ">=3.12"

#  Client CLI dependencies
dependencies = [
    "requests (>=2.33.1,<3.0.0)",
    "pyjwt (>=2.12.1,<3.0.0)",
    "rich (>=13.3.0,<14.0.0)",
    "cryptography (>=48.0.0,<49.0.0)"
]

[tool.project.scripts]
adria = "client.cli:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

# Deployment dependencies
[dependency-groups]
dev = [
    "pytest (>=9.0.3,<10.0.0)"
]
server = [
    "flask (>=3.1.3,<4.0.0)"
]

[tool.pytest.ini_options]
pythonpath = [
  "src"
]

[tool.poetry]
packages = [
    { include = "client", from = "src" },
    { include = "common", from = "src" },
    { include = "metadata_server", from = "src" },
    { include = "storage_node", from = "src" }
]
